# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('coordinator', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.User')),
                ('traveler', models.ManyToManyField(default=1, related_name='traveler', to='login_app.User')),
            ],
        ),
    ]
